name: build

on:
  pull_request:
    branches:
      - master
      - v*

  push:
    branches:
      - master
      - v*
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.17, 1.x]

    name: Go ${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go get -v ./...

      - name: Run tests
        run: go test ./...

  examples:
    runs-on: ubuntu-latest

    name: Examples
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Build examples
        run: cd _examples && go get -v .

      - name: Run examples tests
        run: cd _examples && go test

  formatting:
    runs-on: ubuntu-latest

    name: Formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Check root
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: .
          gofmt-flags: '-s -l'

      - name: Check e2e
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: e2e
          gofmt-flags: '-s -l'

      - name: Check examples
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: _examples
          gofmt-flags: '-s -l'

  linters:
    runs-on: ubuntu-latest

    name: Linters
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: ./...

      - name: Run linters for examples
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          working-directory: _examples

  coverage:
    runs-on: ubuntu-latest
    needs: [build, examples, formatting, linters]

    name: Coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Run tests
        run: go test -covermode=count -coverprofile=coverage.out

      - name: Prepare coverage report
        uses: jandelgado/gcov2lcov-action@v1.0.9

      - name: Send coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
